baseURL = "https://ronanchilvers.github.io/nethea/"
languageCode = "en-gb"
title = "Nethea"
canonifyURLs = true

[taxonomies]
    classification = "classifications"

[params]
    styles = [
        "font-awesome.all.css",
        "bulma.css",
        "bulma-timeline.css",
        "app.css"
    ]
    scripts = [
        "app.js"
    ]
